module.exports = {
  apps: [
    {
      name: "email-worker",
      script: "src/email-worker.ts",
      cwd: "./services/workers",
      interpreter: "bun",
      instances: 2,
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        REDIS_URL: "redis://localhost:6379",
      },
      error_file: "./logs/email-worker-error.log",
      out_file: "./logs/email-worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "sms-worker",
      script: "src/sms-worker.ts",
      cwd: "./services/workers",
      interpreter: "bun",
      instances: 2,
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        REDIS_URL: "redis://localhost:6379",
      },
      error_file: "./logs/sms-worker-error.log",
      out_file: "./logs/sms-worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "cashback-sync",
      script: "src/cashback-sync.ts",
      cwd: "./services/workers",
      interpreter: "bun",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        REDIS_URL: "redis://localhost:6379",
        DATABASE_URL: "postgresql://user:password@localhost:5432/coupon_commerce",
      },
      error_file: "./logs/cashback-sync-error.log",
      out_file: "./logs/cashback-sync-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "click-redirector",
      script: "src/click-redirector.ts",
      cwd: "./services/workers",
      interpreter: "bun",
      instances: 4,
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
        REDIS_URL: "redis://localhost:6379",
        DATABASE_URL: "postgresql://user:password@localhost:5432/coupon_commerce",
      },
      error_file: "./logs/redirector-error.log",
      out_file: "./logs/redirector-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
