"""initial"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '03a11c8e22c7'
down_revision = 'f9bbd940ae62'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'is_available')
    # ### end Alembic commands ###

