"""add_merchant_verification_fields"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05126a8e30da'
down_revision = '65aff6c80477'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('merchants', sa.Column('banner_url', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('business_email', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('business_phone', sa.String(length=20), nullable=True))
    op.add_column('merchants', sa.Column('business_address', sa.Text(), nullable=True))
    op.add_column('merchants', sa.Column('business_city', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('business_state', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('business_pincode', sa.String(length=10), nullable=True))
    op.add_column('merchants', sa.Column('business_country', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('gst_number', sa.String(length=50), nullable=True))
    op.add_column('merchants', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('merchants', sa.Column('bank_account_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('merchants', sa.Column('bank_ifsc_code', sa.String(length=20), nullable=True))
    op.add_column('merchants', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('affiliate_url', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('tracking_url', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('merchants', sa.Column('cashback_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('merchants', sa.Column('platform_commission', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('merchants', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('merchants', sa.Column('verification_status', sa.String(length=30), nullable=False))
    op.add_column('merchants', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.add_column('merchants', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('merchants', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('merchants', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('merchants', sa.Column('total_offers', sa.Integer(), nullable=False))
    op.add_column('merchants', sa.Column('total_clicks', sa.Integer(), nullable=False))
    op.add_column('merchants', sa.Column('total_conversions', sa.Integer(), nullable=False))
    op.add_column('merchants', sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('merchants', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_merchants_user_id'), 'merchants', ['user_id'], unique=False)
    op.create_foreign_key(None, 'merchants', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_merchant', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('merchant_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('merchant_verification_status', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_merchant_id'), 'users', ['merchant_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_merchant_id'), table_name='users')
    op.drop_column('users', 'merchant_id')
    op.drop_column('users', 'merchant_verification_status')
    op.drop_column('users', 'merchant_verified')
    op.drop_column('users', 'is_merchant')
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.drop_index(op.f('ix_merchants_user_id'), table_name='merchants')
    op.drop_column('merchants', 'updated_at')
    op.drop_column('merchants', 'total_revenue')
    op.drop_column('merchants', 'total_conversions')
    op.drop_column('merchants', 'total_clicks')
    op.drop_column('merchants', 'total_offers')
    op.drop_column('merchants', 'is_verified')
    op.drop_column('merchants', 'verified_by')
    op.drop_column('merchants', 'verified_at')
    op.drop_column('merchants', 'verification_notes')
    op.drop_column('merchants', 'verification_status')
    op.drop_column('merchants', 'status')
    op.drop_column('merchants', 'platform_commission')
    op.drop_column('merchants', 'cashback_rate')
    op.drop_column('merchants', 'commission_rate')
    op.drop_column('merchants', 'tracking_url')
    op.drop_column('merchants', 'affiliate_url')
    op.drop_column('merchants', 'website_url')
    op.drop_column('merchants', 'bank_name')
    op.drop_column('merchants', 'bank_ifsc_code')
    op.drop_column('merchants', 'bank_account_number')
    op.drop_column('merchants', 'bank_account_name')
    op.drop_column('merchants', 'pan_number')
    op.drop_column('merchants', 'gst_number')
    op.drop_column('merchants', 'business_country')
    op.drop_column('merchants', 'business_pincode')
    op.drop_column('merchants', 'business_state')
    op.drop_column('merchants', 'business_city')
    op.drop_column('merchants', 'business_address')
    op.drop_column('merchants', 'business_phone')
    op.drop_column('merchants', 'business_email')
    op.drop_column('merchants', 'business_name')
    op.drop_column('merchants', 'banner_url')
    op.drop_column('merchants', 'user_id')
    # ### end Alembic commands ###

