"""fix models"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0a2c0df86c83'
down_revision = '8a0f75bb6a0a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

