"""fix models"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4abea15f4025'
down_revision = '83e77e51394d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_merchants_name', table_name='merchants')
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.create_index('ix_merchants_name', 'merchants', ['name'], unique=True)
    # ### end Alembic commands ###

