"""fix models"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4ff9fbc940e2'
down_revision = '2cb821f1c027'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

