"""initial"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51cb768d7d9e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

