"""new coloumn"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5ac81d8d3c15'
down_revision = '269e62e28857'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

