"""fix models"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '65a346e32c1e'
down_revision = '4abea15f4025'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

