"""new coloumn"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '70dfb77fb21a'
down_revision = 'd5dab3c30391'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referrer_id', sa.Integer(), nullable=False))
    op.add_column('referrals', sa.Column('referred_id', sa.Integer(), nullable=False))
    op.add_column('referrals', sa.Column('referral_code_used', sa.String(length=20), nullable=True))
    op.add_column('referrals', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('referrals', sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('referrals', sa.Column('bonus_paid', sa.Boolean(), nullable=False))
    op.add_column('referrals', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_referrals_referred_user_id', table_name='referrals')
    op.drop_index('ix_referrals_referrer_user_id', table_name='referrals')
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.drop_constraint('referrals_referrer_user_id_fkey', 'referrals', type_='foreignkey')
    op.drop_constraint('referrals_referred_user_id_fkey', 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'users', ['referrer_id'], ['id'])
    op.create_foreign_key(None, 'referrals', 'users', ['referred_id'], ['id'])
    op.drop_column('referrals', 'referred_user_id')
    op.drop_column('referrals', 'referrer_user_id')
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('mobile_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'mobile_verified_at')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'auth_provider')
    op.add_column('referrals', sa.Column('referrer_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('referrals', sa.Column('referred_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key('referrals_referred_user_id_fkey', 'referrals', 'users', ['referred_user_id'], ['id'])
    op.create_foreign_key('referrals_referrer_user_id_fkey', 'referrals', 'users', ['referrer_user_id'], ['id'])
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.create_index('ix_referrals_referrer_user_id', 'referrals', ['referrer_user_id'], unique=False)
    op.create_index('ix_referrals_referred_user_id', 'referrals', ['referred_user_id'], unique=False)
    op.drop_column('referrals', 'completed_at')
    op.drop_column('referrals', 'bonus_paid')
    op.drop_column('referrals', 'bonus_amount')
    op.drop_column('referrals', 'status')
    op.drop_column('referrals', 'referral_code_used')
    op.drop_column('referrals', 'referred_id')
    op.drop_column('referrals', 'referrer_id')
    # ### end Alembic commands ###

