"""auth system"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '767908742ef5'
down_revision = '65d0645cea8f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

