"""new coloumn"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '77a86e25896f'
down_revision = '7397422db297'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

