"""auto_update"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '86f9d562e006'
down_revision = '5c90a02ae1fd'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

