"""auth system"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '895745d63e93'
down_revision = 'daff2b513f96'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

