"""new coloumn"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd108a5fa2417'
down_revision = 'f39206cf76a4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

