"""add_missing_base_commission"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd77359e50bd8'
down_revision = 'e43a0339ebc3'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('base_commission', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('merchants', sa.Column('affiliate_network', sa.String(length=50), nullable=True))
    op.add_column('merchants', sa.Column('affiliate_network_id', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('tracking_url', sa.String(length=1000), nullable=True))
    op.add_column('merchants', sa.Column('show_on_homepage', sa.Boolean(), nullable=False))
    op.add_column('merchants', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('merchants', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'approved_at')
    op.drop_column('merchants', 'status')
    op.drop_column('merchants', 'show_on_homepage')
    op.drop_column('merchants', 'tracking_url')
    op.drop_column('merchants', 'affiliate_network_id')
    op.drop_column('merchants', 'affiliate_network')
    op.drop_column('merchants', 'base_commission')
    # ### end Alembic commands ###

