"""new coloumn"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'daff2b513f96'
down_revision = '70dfb77fb21a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_normalized', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mobile_country_code', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('referred_by_id', sa.Integer(), nullable=True))

    # ---- FIX for NOT NULL Error ----
    op.add_column('users', sa.Column('total_earnings', sa.Numeric(12, 2), nullable=True))
    op.execute("UPDATE users SET total_earnings = 0 WHERE total_earnings IS NULL")
    op.alter_column('users', 'total_earnings', nullable=False)
    # ---------------------------------

    op.add_column('users', sa.Column('status', sa.String(length=30), nullable=True))
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")
    op.alter_column('users', 'status', nullable=False)

    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET failed_login_attempts = 0 WHERE failed_login_attempts IS NULL")
    op.alter_column('users', 'failed_login_attempts', nullable=False)

    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))

    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email_lower', 'users', ['email'], unique=False)
    op.create_index('idx_users_mobile', 'users', ['mobile'], unique=False)
    op.create_index('idx_users_referral_code', 'users', ['referral_code'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_email_normalized'), 'users', ['email_normalized'], unique=True)
    op.create_index(op.f('ix_users_referred_by_id'), 'users', ['referred_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referred_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_normalized'), table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_referral_code', table_name='users')
    op.drop_index('idx_users_mobile', table_name='users')
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'status')
    op.drop_column('users', 'total_earnings')
    op.drop_column('users', 'referred_by_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'mobile_country_code')
    op.drop_column('users', 'email_normalized')
    # ### end Alembic commands ###
