"""initial_schema"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e43a0339ebc3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('traffic_allocation', sa.Float(), nullable=False),
    sa.Column('primary_goal', sa.String(length=100), nullable=True),
    sa.Column('secondary_goals', sa.Text(), nullable=True),
    sa.Column('winner_variant_id', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('statistical_significance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_experiments_name'), 'ab_test_experiments', ['name'], unique=True)
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('banner_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('badge_text', sa.String(length=100), nullable=True),
    sa.Column('badge_color', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('style_metadata', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_id'), 'banners', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('default_tax_rate', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('display_mode', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_visible_in_menu', sa.Boolean(), nullable=False),
    sa.Column('is_visible_in_home', sa.Boolean(), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cohort_type', sa.String(length=50), nullable=False),
    sa.Column('cohort_period', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_departments_slug'), 'departments', ['slug'], unique=True)
    op.create_table('funnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('legal_business_name', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('cin_number', sa.String(length=21), nullable=True),
    sa.Column('msme_number', sa.String(length=20), nullable=True),
    sa.Column('tan_number', sa.String(length=10), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('contact_person_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person_designation', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('registered_address_line1', sa.String(length=255), nullable=True),
    sa.Column('registered_address_line2', sa.String(length=255), nullable=True),
    sa.Column('registered_city', sa.String(length=100), nullable=True),
    sa.Column('registered_state', sa.String(length=100), nullable=True),
    sa.Column('registered_pincode', sa.String(length=6), nullable=True),
    sa.Column('registered_country', sa.String(length=50), nullable=False),
    sa.Column('warehouse_address_line1', sa.String(length=255), nullable=True),
    sa.Column('warehouse_address_line2', sa.String(length=255), nullable=True),
    sa.Column('warehouse_city', sa.String(length=100), nullable=True),
    sa.Column('warehouse_state', sa.String(length=100), nullable=True),
    sa.Column('warehouse_pincode', sa.String(length=6), nullable=True),
    sa.Column('warehouse_country', sa.String(length=50), nullable=False),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('bank_account_type', sa.String(length=20), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tcs_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_fee_per_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_payout_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payout_frequency', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('kyc_status', sa.String(length=30), nullable=False),
    sa.Column('kyc_documents', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('return_policy', sa.Text(), nullable=True),
    sa.Column('return_window_days', sa.Integer(), nullable=False),
    sa.Column('refund_policy', sa.Text(), nullable=True),
    sa.Column('shipping_policy', sa.Text(), nullable=True),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('ships_from_state', sa.String(length=100), nullable=True),
    sa.Column('default_shipping_days', sa.Integer(), nullable=False),
    sa.Column('free_shipping_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cod_enabled', sa.Boolean(), nullable=False),
    sa.Column('cod_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('serviceable_pincodes', sa.Text(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('order_fulfillment_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('return_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cancellation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('seller_tier', sa.String(length=30), nullable=False),
    sa.Column('seller_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('accepts_returns', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.String(length=30), nullable=False),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_merchants_business_type', 'merchants', ['business_type'], unique=False)
    op.create_index('idx_merchants_created_at', 'merchants', ['created_at'], unique=False)
    op.create_index('idx_merchants_rating', 'merchants', ['average_rating'], unique=False)
    op.create_index('idx_merchants_status', 'merchants', ['verification_status'], unique=False)
    op.create_index(op.f('ix_merchants_gstin'), 'merchants', ['gstin'], unique=False)
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=True)
    op.create_index(op.f('ix_merchants_slug'), 'merchants', ['slug'], unique=True)
    op.create_table('newsletter_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('preview_text', sa.String(length=255), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('plain_text_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('clicked_count', sa.Integer(), nullable=False),
    sa.Column('bounced_count', sa.Integer(), nullable=False),
    sa.Column('unsubscribed_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_attempts_expires_at', 'otp_attempts', ['expires_at'], unique=False)
    op.create_index('idx_otp_attempts_identifier', 'otp_attempts', ['identifier'], unique=False)
    op.create_index(op.f('ix_otp_attempts_id'), 'otp_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_otp_attempts_identifier'), 'otp_attempts', ['identifier'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('user_limit', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_id'), 'promo_codes', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_normalized', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('mobile_verified_at', sa.DateTime(), nullable=True),
    sa.Column('mobile_country_code', sa.String(length=5), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pending_cashback', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email_lower', 'users', ['email'], unique=False)
    op.create_index('idx_users_mobile', 'users', ['mobile'], unique=False)
    op.create_index('idx_users_referral_code', 'users', ['referral_code'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_normalized'), 'users', ['email_normalized'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by_id'), 'users', ['referred_by_id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('ab_test_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('traffic_weight', sa.Float(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('avg_revenue_per_user', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_test_experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_variants_experiment_id'), 'ab_test_variants', ['experiment_id'], unique=False)
    op.create_table('affiliate_merchant_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=40), nullable=False),
    sa.Column('external_merchant_id', sa.String(length=120), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_merchant_map_external_merchant_id'), 'affiliate_merchant_map', ['external_merchant_id'], unique=False)
    op.create_index(op.f('ix_affiliate_merchant_map_merchant_id'), 'affiliate_merchant_map', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_affiliate_merchant_map_network'), 'affiliate_merchant_map', ['network'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('page_url', sa.String(length=512), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index('ix_analytics_events_name_date', 'analytics_events', ['event_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index('ix_analytics_events_user_date', 'analytics_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashback_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_cashback', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_rules_category_id'), 'cashback_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_cashback_rules_merchant_id'), 'cashback_rules', ['merchant_id'], unique=False)
    op.create_table('cohort_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('period_offset', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('avg_revenue_per_user', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_metrics_cohort_id'), 'cohort_metrics', ['cohort_id'], unique=False)
    op.create_table('funnel_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_steps_funnel_id'), 'funnel_steps', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_funnel_steps_user_id'), 'funnel_steps', ['user_id'], unique=False)
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('initial_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_cards_code'), 'gift_cards', ['code'], unique=True)
    op.create_table('merchant_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cashback_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_commissions_category_id'), 'merchant_commissions', ['category_id'], unique=False)
    op.create_index(op.f('ix_merchant_commissions_id'), 'merchant_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_commissions_merchant_id'), 'merchant_commissions', ['merchant_id'], unique=False)
    op.create_table('merchant_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_documents_id'), 'merchant_documents', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_documents_merchant_id'), 'merchant_documents', ['merchant_id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_user_id'), 'newsletter_subscribers', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_exclusive', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_code'), 'offers', ['code'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_merchant_id'), 'offers', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_offers_title'), 'offers', ['title'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('order_reference', sa.String(length=100), nullable=True),
    sa.Column('external_order_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cashback_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_password_reset_tokens_token_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_user_id'), 'payouts', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_bestseller', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('how_to_redeem', sa.Text(), nullable=True),
    sa.Column('validity_info', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('push_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=512), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_notifications_user_id'), 'push_notifications', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('referral_code_used', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_family', sa.String(length=36), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_family'), 'refresh_tokens', ['token_family'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('profile_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_provider'), 'social_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_social_accounts_provider_user_id'), 'social_accounts', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('user_2fa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('enabled_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_2fa_user_id'), 'user_2fa', ['user_id'], unique=True)
    op.create_table('user_2fa_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_2fa_logs_user_id'), 'user_2fa_logs', ['user_id'], unique=False)
    op.create_table('user_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_departments_department_id'), 'user_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_departments_user_id'), 'user_departments', ['user_id'], unique=False)
    op.create_table('user_kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('pan_verified', sa.Boolean(), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_kyc_id'), 'user_kyc', ['id'], unique=False)
    op.create_index(op.f('ix_user_kyc_user_id'), 'user_kyc', ['user_id'], unique=True)
    op.create_table('user_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_page_views', sa.Integer(), nullable=False),
    sa.Column('avg_session_duration', sa.Float(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('avg_order_value', sa.Float(), nullable=False),
    sa.Column('total_cashback_earned', sa.Float(), nullable=False),
    sa.Column('favorite_category', sa.String(length=100), nullable=True),
    sa.Column('favorite_merchant', sa.String(length=255), nullable=True),
    sa.Column('purchase_frequency', sa.String(length=50), nullable=True),
    sa.Column('recency_days', sa.Integer(), nullable=True),
    sa.Column('frequency_score', sa.Integer(), nullable=True),
    sa.Column('monetary_score', sa.Integer(), nullable=True),
    sa.Column('rfm_segment', sa.String(length=50), nullable=True),
    sa.Column('predicted_ltv', sa.Float(), nullable=True),
    sa.Column('ltv_segment', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_metrics_user_id'), 'user_metrics', ['user_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('wallet_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_balances_id'), 'wallet_balances', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_balances_user_id'), 'wallet_balances', ['user_id'], unique=True)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_type'), 'wallet_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_requests_user_id'), 'withdrawal_requests', ['user_id'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawals_status'), 'withdrawals', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawals_user_id'), 'withdrawals', ['user_id'], unique=False)
    op.create_table('ab_test_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('conversion_value', sa.Float(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_test_experiments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['ab_test_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_assignments_experiment_id'), 'ab_test_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_ab_test_assignments_session_id'), 'ab_test_assignments', ['session_id'], unique=False)
    op.create_index(op.f('ix_ab_test_assignments_user_id'), 'ab_test_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_ab_test_assignments_variant_id'), 'ab_test_assignments', ['variant_id'], unique=False)
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=40), nullable=False),
    sa.Column('external_click_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tracked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_external_click_id'), 'affiliate_clicks', ['external_click_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_merchant_id'), 'affiliate_clicks', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_network'), 'affiliate_clicks', ['network'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_offer_id'), 'affiliate_clicks', ['offer_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_user_id'), 'affiliate_clicks', ['user_id'], unique=False)
    op.create_table('cashback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_events_user_id'), 'cashback_events', ['user_id'], unique=False)
    op.create_table('newsletter_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['newsletter_campaigns.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['newsletter_subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_deliveries_campaign_id'), 'newsletter_deliveries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_newsletter_deliveries_subscriber_id'), 'newsletter_deliveries', ['subscriber_id'], unique=False)
    op.create_table('offer_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_clicks_id'), 'offer_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_offer_clicks_offer_id'), 'offer_clicks', ['offer_id'], unique=False)
    op.create_table('offer_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_views_id'), 'offer_views', ['id'], unique=False)
    op.create_index(op.f('ix_offer_views_offer_id'), 'offer_views', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_views_user_id'), 'offer_views', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('denomination', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('ab_test_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('goal_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['ab_test_assignments.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_test_experiments.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['ab_test_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_goals_assignment_id'), 'ab_test_goals', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_ab_test_goals_experiment_id'), 'ab_test_goals', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_ab_test_goals_variant_id'), 'ab_test_goals', ['variant_id'], unique=False)
    op.create_table('affiliate_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('click_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=40), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['click_id'], ['affiliate_clicks.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_transactions_click_id'), 'affiliate_transactions', ['click_id'], unique=False)
    op.create_index(op.f('ix_affiliate_transactions_external_transaction_id'), 'affiliate_transactions', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_affiliate_transactions_merchant_id'), 'affiliate_transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_affiliate_transactions_network'), 'affiliate_transactions', ['network'], unique=False)
    op.create_index(op.f('ix_affiliate_transactions_offer_id'), 'affiliate_transactions', ['offer_id'], unique=False)
    op.create_index(op.f('ix_affiliate_transactions_status'), 'affiliate_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_affiliate_transactions_user_id'), 'affiliate_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_transactions_user_id'), table_name='affiliate_transactions')
    op.drop_index(op.f('ix_affiliate_transactions_status'), table_name='affiliate_transactions')
    op.drop_index(op.f('ix_affiliate_transactions_offer_id'), table_name='affiliate_transactions')
    op.drop_index(op.f('ix_affiliate_transactions_network'), table_name='affiliate_transactions')
    op.drop_index(op.f('ix_affiliate_transactions_merchant_id'), table_name='affiliate_transactions')
    op.drop_index(op.f('ix_affiliate_transactions_external_transaction_id'), table_name='affiliate_transactions')
    op.drop_index(op.f('ix_affiliate_transactions_click_id'), table_name='affiliate_transactions')
    op.drop_table('affiliate_transactions')
    op.drop_index(op.f('ix_ab_test_goals_variant_id'), table_name='ab_test_goals')
    op.drop_index(op.f('ix_ab_test_goals_experiment_id'), table_name='ab_test_goals')
    op.drop_index(op.f('ix_ab_test_goals_assignment_id'), table_name='ab_test_goals')
    op.drop_table('ab_test_goals')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_offer_views_user_id'), table_name='offer_views')
    op.drop_index(op.f('ix_offer_views_offer_id'), table_name='offer_views')
    op.drop_index(op.f('ix_offer_views_id'), table_name='offer_views')
    op.drop_table('offer_views')
    op.drop_index(op.f('ix_offer_clicks_offer_id'), table_name='offer_clicks')
    op.drop_index(op.f('ix_offer_clicks_id'), table_name='offer_clicks')
    op.drop_table('offer_clicks')
    op.drop_index(op.f('ix_newsletter_deliveries_subscriber_id'), table_name='newsletter_deliveries')
    op.drop_index(op.f('ix_newsletter_deliveries_campaign_id'), table_name='newsletter_deliveries')
    op.drop_table('newsletter_deliveries')
    op.drop_index(op.f('ix_cashback_events_user_id'), table_name='cashback_events')
    op.drop_table('cashback_events')
    op.drop_index(op.f('ix_affiliate_clicks_user_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_offer_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_network'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_merchant_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_external_click_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_index(op.f('ix_ab_test_assignments_variant_id'), table_name='ab_test_assignments')
    op.drop_index(op.f('ix_ab_test_assignments_user_id'), table_name='ab_test_assignments')
    op.drop_index(op.f('ix_ab_test_assignments_session_id'), table_name='ab_test_assignments')
    op.drop_index(op.f('ix_ab_test_assignments_experiment_id'), table_name='ab_test_assignments')
    op.drop_table('ab_test_assignments')
    op.drop_index(op.f('ix_withdrawals_user_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_status'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_withdrawal_requests_user_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_balances_user_id'), table_name='wallet_balances')
    op.drop_index(op.f('ix_wallet_balances_id'), table_name='wallet_balances')
    op.drop_table('wallet_balances')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_metrics_user_id'), table_name='user_metrics')
    op.drop_table('user_metrics')
    op.drop_index(op.f('ix_user_kyc_user_id'), table_name='user_kyc')
    op.drop_index(op.f('ix_user_kyc_id'), table_name='user_kyc')
    op.drop_table('user_kyc')
    op.drop_index(op.f('ix_user_departments_user_id'), table_name='user_departments')
    op.drop_index(op.f('ix_user_departments_department_id'), table_name='user_departments')
    op.drop_table('user_departments')
    op.drop_index(op.f('ix_user_2fa_logs_user_id'), table_name='user_2fa_logs')
    op.drop_table('user_2fa_logs')
    op.drop_index(op.f('ix_user_2fa_user_id'), table_name='user_2fa')
    op.drop_table('user_2fa')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_provider_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_provider'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_family'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_push_notifications_user_id'), table_name='push_notifications')
    op.drop_table('push_notifications')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_merchant_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payouts_user_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_token_hash', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_offers_title'), table_name='offers')
    op.drop_index(op.f('ix_offers_merchant_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_code'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_newsletter_subscribers_user_id'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_merchant_documents_merchant_id'), table_name='merchant_documents')
    op.drop_index(op.f('ix_merchant_documents_id'), table_name='merchant_documents')
    op.drop_table('merchant_documents')
    op.drop_index(op.f('ix_merchant_commissions_merchant_id'), table_name='merchant_commissions')
    op.drop_index(op.f('ix_merchant_commissions_id'), table_name='merchant_commissions')
    op.drop_index(op.f('ix_merchant_commissions_category_id'), table_name='merchant_commissions')
    op.drop_table('merchant_commissions')
    op.drop_index(op.f('ix_gift_cards_code'), table_name='gift_cards')
    op.drop_table('gift_cards')
    op.drop_index(op.f('ix_funnel_steps_user_id'), table_name='funnel_steps')
    op.drop_index(op.f('ix_funnel_steps_funnel_id'), table_name='funnel_steps')
    op.drop_table('funnel_steps')
    op.drop_index(op.f('ix_cohort_metrics_cohort_id'), table_name='cohort_metrics')
    op.drop_table('cohort_metrics')
    op.drop_index(op.f('ix_cashback_rules_merchant_id'), table_name='cashback_rules')
    op.drop_index(op.f('ix_cashback_rules_category_id'), table_name='cashback_rules')
    op.drop_table('cashback_rules')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index('ix_analytics_events_user_date', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index('ix_analytics_events_name_date', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_affiliate_merchant_map_network'), table_name='affiliate_merchant_map')
    op.drop_index(op.f('ix_affiliate_merchant_map_merchant_id'), table_name='affiliate_merchant_map')
    op.drop_index(op.f('ix_affiliate_merchant_map_external_merchant_id'), table_name='affiliate_merchant_map')
    op.drop_table('affiliate_merchant_map')
    op.drop_index(op.f('ix_ab_test_variants_experiment_id'), table_name='ab_test_variants')
    op.drop_table('ab_test_variants')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_normalized'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_referral_code', table_name='users')
    op.drop_index('idx_users_mobile', table_name='users')
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_promo_codes_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_otp_attempts_identifier'), table_name='otp_attempts')
    op.drop_index(op.f('ix_otp_attempts_id'), table_name='otp_attempts')
    op.drop_index('idx_otp_attempts_identifier', table_name='otp_attempts')
    op.drop_index('idx_otp_attempts_expires_at', table_name='otp_attempts')
    op.drop_table('otp_attempts')
    op.drop_table('newsletter_campaigns')
    op.drop_index(op.f('ix_merchants_slug'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_gstin'), table_name='merchants')
    op.drop_index('idx_merchants_status', table_name='merchants')
    op.drop_index('idx_merchants_rating', table_name='merchants')
    op.drop_index('idx_merchants_created_at', table_name='merchants')
    op.drop_index('idx_merchants_business_type', table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('funnels')
    op.drop_index(op.f('ix_departments_slug'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_banners_id'), table_name='banners')
    op.drop_table('banners')
    op.drop_index(op.f('ix_ab_test_experiments_name'), table_name='ab_test_experiments')
    op.drop_table('ab_test_experiments')
    # ### end Alembic commands ###

