"""fix models"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e84953b337ac'
down_revision = '05126a8e30da'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

